version: '3.8'

services:
  health_api:
    build: ./health_api
    container_name: health_api
    volumes:
      - ./html:/html:ro
    environment:
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=my-super-secret-auth-token
      - INFLUX_ORG=my-org
      - INFLUX_BUCKET=health
    restart: unless-stopped
    networks:
      - global_infra

  health_ingest:
    build: ./health_ingest
    container_name: health_ingest
    volumes:
      - ./Apple_Health:/data:ro
    environment:
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=my-super-secret-auth-token
      - INFLUX_ORG=my-org
      - INFLUX_BUCKET=health
    restart: "no"
    networks:
      - global_infra

networks:
  global_infra:
    external: true
